### ISSUE TITLE
Dev and build mode not working

### ISSUE THREAD

**Issue by cawa-93** [element-plus/element-plus-nuxt#36]
Just to try start site in dev mode and got this error:

```
[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/popper-root/index" from "virtual:nuxt:C:\Users\kozac\Dev\blog_kyivska_zefirka\.nuxt\components.client.mjs". Does the file exist?

virtual:nuxt:C:/Users/kozac/Dev/blog_kyivska_zefirka/.nuxt/components.client.mjs:214:31

212|  export { ElPopover } from "element-plus/es/components/popover/index";
213|  export const LazyElPopover = defineAsyncComponent(() => import("element-plus/es/components/popover/index" /* webpackChunkName: "components/el-popover" */).then(c => c['ElPopover']))
214|  export { ElPopperRoot } from "element-plus/es/components/popper-root/index";
   |                                ^
215|  export const LazyElPopperRoot = defineAsyncComponent(() => import("element-plus/es/components/popper-root/index" /* webpackChunkName: "components/el-popper-root" */).then(c => c['ElPopperRoot']))
216|  export { ElProgress } from "element-plus/es/components/progress/index";

    at formatError (file:///C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41389:46)
    at TransformContext.error (file:///C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41385:19)
    at normalizeUrl (file:///C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39693:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.transform (file:///C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39826:47)
    at async Object.transform (file:///C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41660:30)
    at async loadAndTransform (file:///C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep
```

nuxt config is 
```js
export default defineNuxtConfig({
  typescript: {
    strict: true,
    shim: false,
  },

  // build modules
  modules: [
    '@element-plus/nuxt',
    '@nuxt/content',
  ],
})
```

Same on `build` command

```
i Building client...                                                                                                                                                                                              17:20:29
vite v4.1.1 building for production...
✓ 313 modules transformed.
[vite]: Rollup failed to resolve import "element-plus/es/components/popper-root/index" from "virtual:nuxt:C:/Users/kozac/Dev/blog_kyivska_zefirka/.nuxt/components.client.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

 ERROR  [vite]: Rollup failed to resolve import "element-plus/es/components/popper-root/index" from "virtual:nuxt:C:/Users/kozac/Dev/blog_kyivska_zefirka/.nuxt/components.client.mjs".                           17:20:34  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (/C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44772:19)
  at onwarn (/C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44542:13)
  at Object.onwarn (/C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/rollup/dist/es/shared/rollup.js:24641:13)
  at ModuleLoader.handleInvalidResolvedId (/C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/rollup/dist/es/shared/rollup.js:23325:26)
  at /C:/Users/kozac/Dev/blog_kyivska_zefirka/node_modules/rollup/dist/es/shared/rollup.js:23285:26
```

"@element-plus/nuxt": "1.0.3",
"element-plus": "2.2.27"

**Comment by tolking** [comment]
Fixed in [element-plus 11383](https://github.com/element-plus/element-plus/pull/11383), you can update `element-plus` to the latest version.
