### ISSUE TITLE
Error on nuxt 3.6.2

### ISSUE THREAD

**Issue by ridhansholeh** [element-plus/element-plus-nuxt#61]
when i upgrade nuxt to latest version (3.6.2) i got error

`Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function`

```
 _dayjs.default.extend is not a function

  at node_modules/element-plus/es/components/time-picker/src/time-picker.mjs:10:16
  at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
  at jiti (node_modules/jiti/dist/jiti.js:1:253034)
  at node_modules/element-plus/es/components/time-picker/index.mjs:1:2184
  at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
  at jiti (node_modules/jiti/dist/jiti.js:1:253034)
  at node_modules/element-plus/es/components/calendar/src/date-table.mjs:2:1
  at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
  at jiti (node_modules/jiti/dist/jiti.js:1:253034)
  at node_modules/element-plus/es/components/calendar/src/date-table2.mjs:3:18
```

**Comment by tolking** [comment]
I used the [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter) and upgraded all dependencies to the latest without reproducing any errors

**Comment by ridhansholeh** [comment]
i am using nuxt version 2.5.3, element-plus version 2.3.6 and @element-plus/nuxt version 1.0.5. and then i upgraded nuxt to 2.6.2 using `npx nuxi upgrade --force` command and it shows error like that
but when I use the command `npm install nuxt -D` to upgrade nuxt, no error appears but it becomes a lot of bugs in nuxt
what command did you use to upgrade the nuxt version to 2.6.2?

this is my tsconfig.json
```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "noImplicitAny": false,
    "target": "ESNext",
    "module": "ESNext",
    "baseUrl": ".",
    "types": ["element-plus/global", "vite/client", "vite-plugin-pwa/client"],
    "lib": ["ESNext"]
  }
}
```
is there something wrong with tsconfig.json?

**Comment by tolking** [comment]
pnpm up

You can check for differences from the [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter)

**Comment by shroomlife** [comment]
Have the same issue. Here are my packages:

```
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "6.4.0",
    "@fortawesome/free-brands-svg-icons": "6.4.0",
    "@fortawesome/free-regular-svg-icons": "6.4.0",
    "@fortawesome/free-solid-svg-icons": "6.4.0",
    "@fortawesome/vue-fontawesome": "3.0.3",
    "@pinia/nuxt": "0.4.11",
    "bootstrap": "5.3.1",
    "moment": "2.29.4",
    "moment-timezone": "0.5.43",
    "node-emoji": "2.1.0",
    "pinia": "2.1.6"
  },
  "devDependencies": {
    "@element-plus/nuxt": "1.0.5",
    "@nuxt/types": "2.17.1",
    "@types/node": "20.4.5",
    "element-plus": "2.3.8",
    "nuxt": "3.6.5",
    "sass": "1.64.2",
    "typescript": "5.1.6"
  },
```

And I use the following Dockerfile:

```
FROM node:20-alpine AS builder

ENV NODE_ENV=development

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . .

RUN npm install
RUN npm run build
```

And get the following error:

```
 > [builder 5/6] RUN npm install:
13.85
13.85 > vype-website@1.2.0 postinstall
13.85 > nuxt prepare
13.85
13.92 Nuxi 3.6.5
16.83
16.83  ERROR  Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function
16.83
16.83
16.83  ERROR  _dayjs.default.extend is not a function
16.83
16.83   at node_modules/element-plus/es/components/time-picker/src/time-picker.mjs:10:16
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/element-plus/es/components/time-picker/index.mjs:1:2184
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/element-plus/es/components/calendar/src/date-table.mjs:2:1
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/element-plus/es/components/calendar/src/date-table2.mjs:3:18
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/element-plus/es/components/calendar/src/calendar2.mjs:4:41
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/element-plus/es/components/calendar/index.mjs:2:40
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/element-plus/es/component.mjs:9:15
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at node_modules/@element-plus/nuxt/dist/module.mjs:2:41
16.83   at evalModule (node_modules/jiti/dist/jiti.js:1:255106)
16.83   at jiti (node_modules/jiti/dist/jiti.js:1:253034)
16.83   at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2244:26)
16.83   at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2435:90)
16.83   at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2408:47)
16.83   at async initNuxt (node_modules/nuxt/dist/index.mjs:3238:7)
16.83   at async loadNuxt (node_modules/nuxt/dist/index.mjs:3314:5)
16.83   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
16.83   at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
16.83   at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

I already tried to add dayjs to my repository but that didn't help.

Any tips?

**Comment by tolking** [comment]
try delete package-lock.json and reinstall packages

**Comment by shroomlife** [comment]
Here is my `.dockerignore` contents:

```
node_modules
.output
.nuxt
.git
.env
package-lock.json
```

There is no `package-lock.json` file present on time of `npm install`

**Comment by foxted** [comment]
Facing the same issue on a fresh install of Nuxt 3.

**Comment by foxted** [comment]
Nevermind, the issue is still there. I am baffled: when I use the version of the package I have locally in the package.json of my app, works fine, but when installing the dependency directly via npm, it breaks. Any ideas where it could come from? Could anything be missing in the final `dist/` folder?
